name: LinkPlayerCount
api: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6]
version: 1.0.0
depend: SignServerStats
load: POSTWORLD
main: robske_110\LPC\LinkPlayerCount
author: robske_110

commands:
 linkplayercount add:
  description: Adds a sepecified server
  usage: "/linkplayercount add <hostname> [port]"
  permission: LinkPlayerCount.manageList
  aliases: [addLPC, addlpc, lpcadd, LPCadd, lpc add, LPC add]
 linkplayercount rem:
  description: Removes a sepecified server
  usage: "/linkplayercount rem <hostname> [port]"
  permission: LinkPlayerCount.manageList
  aliases: [remLPC, remlpc, lpcrem, LPCrem, lpc rem, LPC rem, linkplayercount remove]
permissions:
 LinkPlayerCount:
  description: "Allows to use all LinkPlayerCount features"
  default: false
  children:
   LinkPlayerCount.manageList:
    description: "Users with this permission will be able to add/remove servers."
