name: LinkPlayerCount
api: 3.0.0
version: 1.0.0
depend: SignServerStats
load: POSTWORLD
main: robske_110\LPC\LinkPlayerCount
author: robske_110

commands:
 linkplayercount add:
  description: Adds a sepecified server
  usage: "/linkplayercount add <hostname> [port]"
  permission: LinkPlayerCount.manageList
  aliases: [lpc add, lpcadd]
 linkplayercount rem:
  description: Removes a sepecified server
  usage: "/linkplayercount rem <hostname> [port]"
  permission: LinkPlayerCount.manageList
  aliases: [lpc rem, lpcrem]
permissions:
 LinkPlayerCount:
  description: "Allows to use all LinkPlayerCount features"
  default: false
  children:
   LinkPlayerCount.manageList:
    description: "Users with this permission will be able to add/remove servers."
    default: op