name: StatusList
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6]
version: 1.1.0
depend: SignServerStats
load: POSTWORLD
main: robske_110\SL\StatusList
author: robske_110

commands:
 statuslist add:
  description: Adds a sepecified server to the statuslist
  usage: "/statuslist add <hostname> [port]"
  permission: StatusList.manageList
  aliases: [addSL, addsl, SLadd, sladd, addSserver, addStatusS, sl add, SL add]
 statuslist rem:
  description: Removes a sepecified server from the statuslist
  usage: "/statuslist rem <hostname> [port]"
  permission: StatusList.manageList
  aliases: [remSL, remsl, SLrem, slrem, remSserver, remStatusS, sl rem, SL rem, statuslist remove]
 statuslist show:
   description: Shows all servers on the statuslist
   usage: "/statuslist show <hostname> [port]"
   permission: StatusList.seeList
   aliases: [showSL, showsl, SLshow, slshow, listStatusList, showStatusList, sl show, SL show, statuslist list]

permissions:
 StatusList:
  description: "Allows to use all StatusList features"
  children:
   StatusList.seeList:
    description: "Users with this permission will be able to see the statuslist."
   StatusList.manageList:
    description: "Users with this permission will be able to add/remove servers from the statuslist."
