name: WarnOffline
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
version: 1.1.0
depend: StatusList
load: POSTWORLD
main: robske_110\WO\WarnOffline
author: robske_110

permissions:
 WarnOffline:
  description: "Allows to use all WarnOffline features"
  children:
   WarnOffline.notify:
    description: "Users with this permission will be notified if a server from the statuslist goes down."