name: SignServerStats
api: 
- 3.0.0
- 3.0.1
- 3.0.2
- 3.0.3
- 3.0.4
- 3.0.5
- 3.0.6
version: 1.1.0
load: POSTWORLD
main: robske_110\SSS\SignServerStats
author: robske_110

permissions:
 SSS:
  description: "Allows to use all SSS features"
  children:
   SSS.signs:
     description: "Allows to create [SSS] signs and destroy them"
   SSS.servertransfer:
     description: "Allows to click on a SSSign and get transferred to that server."
